// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE
'use strict';


var darkBlue = "#2E3B4B";

var white = "#f0f2f5";

var grey = "#dee3e8";

var teal = "#287b97";

exports.darkBlue = darkBlue;
exports.white = white;
exports.grey = grey;
exports.teal = teal;
/* No side effect */
