// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");
var Style$ReactNative = require("reason-react-native/src/apis/Style.bs.js");
var Colors$ReactTemplate = require("./Colors.bs.js");

var FontSize = /* module */[
  /* large */"96px",
  /* medium */"64px",
  /* small */"32px"
];

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: Colors$ReactTemplate.darkBlue,
        height: Style$ReactNative.pct(100)
      }
    });

exports.FontSize = FontSize;
exports.styles = styles;
/* styles Not a pure module */
