// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var Colors$ReactTemplate = require("./Colors.bs.js");
var StyleSheet$BsReactNative = require("bs-react-native/src/styleSheet.js");

var FontSize = /* module */[
  /* large */"96px",
  /* medium */"64px",
  /* small */"32px"
];

var styles = StyleSheet$BsReactNative.create({
      container: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.height(/* Pct */Block.__(1, [100])),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, [Colors$ReactTemplate.darkBlue])),
              /* [] */0
            ]
          ])
    });

exports.FontSize = FontSize;
exports.styles = styles;
/* styles Not a pure module */
