// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function rates(curr) {
  switch (curr) {
    case 0 : 
        return "USD";
    case 1 : 
        return "BTC";
    case 2 : 
        return "LTC";
    case 3 : 
        return "JPY";
    case 4 : 
        return "ETH";
    case 5 : 
        return "EUR";
    
  }
}

function filtered(list) {
  return Belt_List.reduce(list, Belt_MapString.empty, (function (acc, p) {
                return Belt_MapString.update(acc, p[/* currency */0], (function (param) {
                              if (param !== undefined) {
                                var places = param;
                                var match = p[/* currency */0];
                                switch (match) {
                                  case "BTC" : 
                                  case "ETH" : 
                                  case "EUR" : 
                                  case "JPY" : 
                                  case "LTC" : 
                                  case "USD" : 
                                      return /* :: */[
                                              p,
                                              places
                                            ];
                                  default:
                                    throw [
                                          Caml_builtin_exceptions.match_failure,
                                          /* tuple */[
                                            "FxFilter.re",
                                            29,
                                            8
                                          ]
                                        ];
                                }
                              } else {
                                return /* :: */[
                                        p,
                                        /* [] */0
                                      ];
                              }
                            }));
              }));
}

exports.rates = rates;
exports.filtered = filtered;
/* No side effect */
