// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE
'use strict';


function rates(curr) {
  switch (curr) {
    case 0 : 
        return "USD";
    case 1 : 
        return "BTC";
    case 2 : 
        return "LTC";
    case 3 : 
        return "JPY";
    case 4 : 
        return "ETH";
    case 5 : 
        return "EUR";
    
  }
}

exports.rates = rates;
/* No side effect */
