// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var Utils$ReactTemplate = require("../utils/Utils.bs.js");
var Colors$ReactTemplate = require("../styles/Colors.bs.js");
var StyleSheet$BsReactNative = require("bs-react-native/src/styleSheet.js");

var styles = StyleSheet$BsReactNative.create({
      container: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.width(/* Pct */Block.__(1, [100])),
            /* :: */[
              Style$BsReactNative.padding(/* Pt */Block.__(0, [20])),
              /* [] */0
            ]
          ]),
      currencyWrapper: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.padding(/* Pt */Block.__(0, [20])),
            /* :: */[
              Style$BsReactNative.flexDirection(/* Row */0),
              /* :: */[
                Style$BsReactNative.justifyContent(/* SpaceBetween */5),
                /* :: */[
                  Style$BsReactNative.alignItems(/* Center */2),
                  /* :: */[
                    Style$BsReactNative.borderBottomWidth(1),
                    /* :: */[
                      Style$BsReactNative.borderBottomColor(/* String */Block.__(0, [Colors$ReactTemplate.teal])),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]),
      currency: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [32])),
            /* :: */[
              Style$BsReactNative.fontWeight(/* _100 */1055956338),
              /* :: */[
                Style$BsReactNative.color(/* String */Block.__(0, [Colors$ReactTemplate.grey])),
                /* :: */[
                  Style$BsReactNative.letterSpacing(4),
                  /* [] */0
                ]
              ]
            ]
          ])
    });

var Styles = /* module */[/* styles */styles];

var component = ReasonReact.statelessComponent("FxItem");

function make(item, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.currency), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils$ReactTemplate.nullableStringToElement(item.currency)])),
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Caml_option.some(styles.currency), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils$ReactTemplate.nullableStringToElement(item.rate)]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* styles Not a pure module */
