// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE
'use strict';

var ListLabels = require("bs-platform/lib/js/listLabels.js");

function s(prim) {
  return prim;
}

function nullableStringToElement(obj) {
  if (obj !== undefined) {
    return obj;
  } else {
    return "No data";
  }
}

function filter(f, list) {
  return ListLabels.filter(f)(list);
}

var find = ListLabels.find;

exports.s = s;
exports.nullableStringToElement = nullableStringToElement;
exports.filter = filter;
exports.find = find;
/* No side effect */
