// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ReactApollo = require("react-apollo");
var ReactNative = require("react-native");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");
var Styles$ReactTemplate = require("./styles/Styles.bs.js");
var ExchangeRateView$ReactTemplate = require("./components/ExchangeRateView.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);

var httpLink = ApolloLinks.createHttpLink("https://48p1r2roz4.sse.codesandbox.io", undefined, undefined, undefined, undefined, undefined, /* () */0);

var instance = ReasonApollo.createApolloClient(httpLink, inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);

function app(param) {
  return React.createElement(ReactApollo.ApolloProvider, {
              client: instance,
              children: React.createElement(ReactNative.View, {
                    style: Styles$ReactTemplate.styles.container,
                    children: React.createElement(ExchangeRateView$ReactTemplate.make, { })
                  })
            });
}

exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.instance = instance;
exports.app = app;
/* inMemoryCache Not a pure module */
